fakereddit/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :subs 
  resources :posts, except: [:index] do 
    resources :comments, only: [:new]
  end 
  resources :comments, only: [:create, :edit, :update, :destroy, :show]
end

fakereddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord 

  validates :title, :author_id, presence: true 

 
  has_many :postsubs,
  primary_key: :id,
  foreign_key: :post_id,
  class_name: :Postsub,
  dependent: :destroy,
  inverse_of: :post


  has_many :subs,
  through: :postsubs,
   source: :sub

  belongs_to :author, 
    primary_key: :id, 
    foreign_key: :author_id, 
    class_name: :User

  has_many :comments, 
  dependent: :destroy


end 

fakereddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController 

  before_action :ensure_logged_in, only: [:new, :destroy]
  def new 
    @post = Post.new
    render :new
  end 

  def create
    @post = Post.new(post_params)
     
    @post.author_id = current_user.id
    # @post.sub_ids = post_params[:sub_ids]
    if @post.save
      
      redirect_to subs_url
    else
      flash.now[:errors] = @post.errors.full_messages 
      render :new
    end  
  end 

  def show 
    @post = Post.find(params[:id])
    render :show
  end 

  def edit 
    @post = current_user.posts.find_by(id: params[:id])
    if @post 
      render :edit 
    else 
      flash[:errors] = ["Cannot update a post that is not yours"]
      redirect_to post_url(params[:id])
    end 
  end 

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    if @post
      @post.destroy
      flash[:errors] = ['Post was deleted!']
      redirect_to subs_url
    else
      flash[:errors] = ['You can only delete your own posts']
      redirect_to post_url(params[:id])
    end
  end 

  private 

  def post_params 
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end 

end 

fakereddit/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action="<%= post_url(@post) %>" method='POST'>
<input type="hidden" name="_method" value="PATCH">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>
    Title
    <input type="text" name="post[title]" value='<%= @post.title %>'>
  </label>

    <label>
    URL
    <input type="text" name="post[url]" value='<%= @post.url %>'>
  </label>

  <label>
    Content
    <input type="text" name="post[content]" value='<%= @post.content %>'>
  </label>

    <input type="hidden" name='post[sub_ids][]' value=''>


    <% Sub.all.each do |sub|  %>
      <label>
          <input type="checkbox" name="post[sub_ids][]" value='<%= sub.id %>' <%= "checked" if @post.sub_ids.include?(sub.id) %>>
          <%= sub.title %>
      </label>
    <% end %>




  <button type="submit">Submit</button>

</form>

fakereddit/app/views/posts/new.html.erb
<h2>New Post</h2>

<a href="<%= subs_url %>">All Subs</a>

<form action="<%= posts_url %>" method='POST'>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    
  <label>
    Title
    <input type="text" name="post[title]">
  </label>

  <label>
    URL
    <input type="text" name="post[url]">
  </label>

  <label>
    Content
    <input type="text" name="post[content]">
  </label>


    <% Sub.all.each do |sub|  %>
      <label>
          <input type="checkbox" name="post[sub_ids][]" value='<%= sub.id %>'>
          <%= sub.title %>
      </label>
    <% end %>


  <button type="submit">Submit</button>

</form>

fakereddit/app/views/posts/show.html.erb
<a href="<%= edit_post_url(@post) %>">Edit Post</a>
<br>
<a href="<%= subs_url %>">All Subs!</a>
<p>
  <%= @post.title %>
  <%= @post.url %>
  <%= @post.content %>
  <p>- <%= @post.author.username %></p>
</p>

<% @post.comments.each do |comment| %>
  <a href="<%= comment_url(comment) %>"><p><%= comment.content if comment.parent_comment_id.nil? %></p></a>
<% end %>

<a href="<%= new_post_comment_url(@post.id) %>">New Comment</a>