fakereddit/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :subs 
  resources :posts, except: [:index] do 
    resources :comments, only: [:new]
  end 
  resources :comments, only: [:create, :edit, :update, :destroy, :show]
end

fakereddit/app/models/comment.rb
class Comment < ApplicationRecord 
  validates :content, :author_id, :post_id, presence: true 

  belongs_to :author,
    primary_key: :id, 
    foreign_key: :author_id, 
    class_name: :User 

  belongs_to :post 

  belongs_to :parent_comment, 
    primary_key: :id, 
    foreign_key: :parent_comment_id, 
    class_name: :Comment, 
    optional: true 

  has_many :comments, 
    primary_key: :id, 
    foreign_key: :parent_comment_id, 
    class_name: :Comment, 
    dependent: :destroy

end 

fakereddit/app/controllers/comments_controller.rb
class CommentsController < ApplicationController 
  before_action :ensure_logged_in, except: [:show] 
def new
  @comment = Comment.new 
  render :new 
end 

def create 
  @comment = Comment.new(comment_params)
  @comment.author_id = current_user.id
  @comment.post_id = params[:post_id]
  @comment.parent_comment_id = params[:parent_comment_id]
  if @comment.save
    redirect_to post_url(params[:post_id])
  else
    @comment = Comment.new(comment_params)
    flash.now[:errors] = @comment.errors.full_messages
    render :new
  end

end 

def edit 
  @comment = current_user.comments.find_by(id: params[:id])
  render :edit 
end 

def update
  @comment = current_user.comments.find_by(id: params[:id])
  if @comment.update_attributes(comment_params)
    redirect_to comment_url(@comment)
  else
    flash[:errors] = ["You cant edit other peoples comments "]
    redirect_to comment_url(@comment)
  end
end 

def destroy
  @comment = current_user.comments.find_by(id: params[:id])
  post_id = @comment.post_id
  @comment.destroy
  flash[:errors] = ['comment was deleted ']
  redirect_to post_url(post_id)
end 

def show
  @comment = Comment.find(params[:id])
  render :show
end 

private 

def comment_params 
  params.require(:comment).permit(:content)
end 

end 

fakereddit/app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<a href="<%= post_url(@comment.post_id) %>">POST</a>

<form action="<%= comment_url(@comment) %>" method='POST'>
  <input type="hidden" name="_method" value='PATCH'>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Comment
    <input type="text" name="comment[content]" value='<%= @comment.content %>'>
  </label>

  <button type="submit">Submit Changes</button>

</form>

fakereddit/app/views/comments/new.html.erb
<h2>New Comment</h2>

<a href="<%= post_url(params[:post_id]) %>">POST</a>

<form action="<%= comments_url %>" method='POST'>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <% if params[:parent_comment_id] %>
    <input type="hidden" name="parent_comment_id" value='<%= params[:parent_comment_id] %>'>
  <% end %>
  
  <label>
    Comment
    <input type="text" name="comment[content]">
  </label>

  <input type="hidden" name="post_id" value='<%= params[:post_id] %>'>


  <button type="submit">Submit Comment</button>

</form>

fakereddit/app/views/comments/show.html.erb
<p>
  <%= @comment.content %>
  <br>
  by: <%= @comment.author.username %>
</p>

<a href="<%= post_url(@comment.post_id) %>">OG Post</a>
<a href="<%= edit_comment_url(@comment) %>">Edit ME!</a>


<h3>Replies</h3>

<form action="<%= new_post_comment_url(@comment.post_id) %>">
  <input type="hidden" name="parent_comment_id" value='<%= @comment.id %>'>
  <button type="submit">Add Reply</button>
</form>
<p>
  <% @comment.comments.each do |babies| %>
    <%= babies.content %>
    by: <%= babies.author.username %>
   <a href="<%= edit_comment_url(babies) %>">Edit ME!</a>
    <br>
    <% end %>
</p>