fakereddit/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :subs 
  resources :posts, except: [:index] do 
    resources :comments, only: [:new]
  end 
  resources :comments, only: [:create, :edit, :update, :destroy, :show]
end

fakereddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord 

  validates :title, :description, :moderator_id, presence: true 

  belongs_to :moderator, 
    primary_key: :id, 
    foreign_key: :moderator_id, 
    class_name: :User 

  has_many :postsubs,
  primary_key: :id,
  foreign_key: :sub_id,
  class_name: :Postsub,
  dependent: :destroy,
  inverse_of: :sub

  has_many :posts,
  through: :postsubs,
  source: :post

end 

fakereddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController 

  before_action :ensure_logged_in, only: [:new, :edit, :destroy]

  def new 
    @sub = Sub.new 
    render :new 
  end 

  def create 
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end 

  def edit 
    @sub = current_user.moderated_subs.find_by(id: params[:id])
    # @sub = Sub.find(params[:id])
    if @sub # && @sub.moderator_id == current_user.id 
      render :edit 
    else
      flash[:errors] = ["You cannot modify someone elses subs"]
      redirect_to sub_url(params[:id])
    end
  end 

  def update 
    @sub = Sub.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end 

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    flash[:errors] = ['Sub was destroyed']
    redirect_to subs_url  
  end 

  def index 
    @subs = Sub.all 
    render :index
  end 

  def show
    @sub = Sub.find(params[:id])
    render :show 
  end 


  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end 
end 

fakereddit/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<a href="<%= sub_url(@sub) %>">Return to Sub Page</a>


<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">

  <label>Title 
  <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description 
  <textarea name="sub[description]" id="" cols="30" rows="10"><%= @sub.description %></textarea>
  </label>

  <button type="submit">Create Sub</button>
 
</form>

fakereddit/app/views/subs/index.html.erb
<h1>Hello, this is the subs page</h1>

<a href="<%= new_sub_url %>">Create a Sub</a>

<ul>
  <% @subs.each do |sub| %>
  <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <% end %>
</ul>

fakereddit/app/views/subs/new.html.erb
<form action="<%= subs_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title 
  <input type="text" name="sub[title]">
  </label>

  <label>Description 
  <textarea name="sub[description]" id="" cols="30" rows="10"></textarea>
  </label>

  <button type="submit">Create Sub</button>

</form>

fakereddit/app/views/subs/show.html.erb
<a href="<%= subs_url %>">All Subs</a>

<a href="<%= edit_sub_url(@sub) %>"><h1><%= @sub.title %></h1></a>

<p>moderator: <%= @sub.moderator.username %></p>

<%= @sub.description %>

<ul>
  <% @sub.posts.each do |post| %>
    <li><a href="<%= post_url(post) %>"><%= post.title %></a> - <%= post.content %> - <%= post.author.username %></li>
  <% end %>
</ul>

<a href="<%= new_post_url %>">Add a Post</a>